import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar';
import Hero from './components/hero/Hero';
import Footer from './components/footer/Footer';
import { BrowserRouter, Routes, Route, useLocation} from 'react-router-dom';
import { useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


export default function Home() {
  const [openModalLogin, setOpenModalLogin] = useState(false)
  const [openModalRegister, setOpenModalRegister] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marcopolo__favicon.png" />
      </Head>
      {/* <h1>tes</h1> */}
      <div className='home'>
      <Hero />
      </div>
      
    </>
  )
}
