import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar';
import {Home as Homes }from './Home';
import Article from './Article';
import ArticlePage from './ArticlePage';
import Category from './Category';
import Testi from './Testi';
import Footer from './components/footer/Footer';
import { BrowserRouter, Routes, Route, useLocation} from 'react-router-dom';
import { useState, useEffect } from 'react'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


export default function Home() {
  const [openModalLogin, setOpenModalLogin] = useState(false)
  const [openModalRegister, setOpenModalRegister] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>tes</h1> */}
      {/* <BrowserRouter basename='/'> */}

     <Navbar />
      
      {/* <Routes>
      <Route exact path="/" element={<Homes openModalLogin={openModalLogin} setOpenModalLogin={setOpenModalLogin} openModalRegister={openModalRegister} setOpenModalRegister={setOpenModalRegister}/>} />
      <Route exact path="/article" element={<Article />} />
      <Route exact path="/article/:id" element={<ArticlePage />} />
      <Route exact path="/category/:categoryId" element={<Category />} />
      <Route exact path="/testimoni" element={<Testi />} />
      </Routes>
      <Footer />
      </BrowserRouter> */}
    </>
  )
}
